name: uremit
description: A new Flutter project.

publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For iOS icons
  cupertino_icons: ^1.0.2

  # To incorporate the SVGs in Flutter
  flutter_svg: ^1.0.1

  # For Dynamic Screen Sizes
  flutter_screenutil: ^5.3.1

  # For creating simple shadow
  simple_shadow: ^0.3.0

  # For Google Fonts
  google_fonts: ^2.2.0

  # For dependency injection
  get_it: ^7.2.0

  # For state management
  provider: ^6.0.2

  # For virtual different screen sizes
  device_preview: ^1.0.0

  # For Equality overriding
  equatable: ^2.0.3

  # For reactive programming
  dartz: ^0.10.1

  # For checking the internet connection
  internet_connection_checker: ^0.0.1+3

  # For image selection from gallery or storage
  image_picker: ^0.8.5+3

  logger: any
  # For file selection from storage
  file_picker: ^4.3.2

  # For encryption to requests or responses
  encrypt: ^5.0.1

  # For securely storing the data in device
  flutter_secure_storage: ^5.0.2

  # For making HTTP requests
  dio: ^4.0.4

  # For loading images from network and storing theme in cache
  cached_network_image: ^3.2.0

  # For showing toast messages
  fluttertoast: ^8.0.8

  # For making internationalization in app
  intl: ^0.17.0

  # For launching other applications like browser
  url_launcher: ^6.1.2

  # For bottom nav bar and as a tab view on the page views
  animated_bottom_navigation_bar: ^0.3.2

  # For masking input form fields like (03xx-xxxxxxx)
  mask_text_input_formatter: ^2.1.0

  # For page animations
  animations: ^2.0.2

  # For checking the password strength
  password_strength: ^0.2.0

  # For getting multiple value listenable builders
  multi_value_listenable_builder: ^0.0.2

  # For OTP Code
  pin_code_fields: ^7.4.0

  # For animated dialog
  flutter_animated_dialog: ^2.0.1

  # For carousel sliders
  carousel_slider: ^4.0.0

  # For toggle buttons
  toggle_switch: ^1.4.0

  # For dotted lines
  dotted_line: ^3.1.0

  # For expansion tiles
  expansion_tile_card: ^2.0.0

  # For Device Information
  device_info_plus: ^3.2.2

  # For device's IMEI
  unique_identifier: ^0.2.2

  # For currency formatting
  currency_text_input_formatter: ^2.1.5

  # For shimmer effects
  shimmer: ^2.0.0

  # For expansion page view
  expandable_page_view: ^1.0.13

  # For page dot indicators
  smooth_page_indicator: ^1.0.0+2

  # For radio group buttons
  radio_group_v2: ^1.0.2

  #For on/off indication of button
  flutter_switch: ^0.3.2

  # for opening files
  open_file: ^3.2.1

  #to provide paths of different directories on mobile
  path_provider: ^2.0.10

  #to get differnet permissions from user
  permission_handler: ^9.2.0

  #to take screenshot of a widget
  screenshot: ^1.2.3

  # to share files
  share_plus: ^4.0.4

  # to store image
  image_gallery_saver: '^1.7.1'

  # to show web browsers
  webview_flutter: ^3.0.4

  network_info_plus: ^2.1.3

  phone_numbers_parser: ^7.0.0

  country_calling_code_picker: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: BottomNavBarIcons
      fonts:
        - asset: assets/fonts/BottomNavBarIcons.ttf
